// Code generated by Wire. DO NOT EDIT.

package wire

import (
	"IAM/repository"
	"IAM/routers/api"
	"IAM/service"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitializeApplicationController(db *gorm.DB) api.ApplicationController {
	applicationRepository := repository.NewApplicationRepository(db)
	applicationService := service.NewApplicationService(applicationRepository)
	applicationController := api.NewApplicationController(applicationService)
	return applicationController
}
